### ISSUE TITLE
Update to version v2.0.0

### ISSUE THREAD

**Issue by WaveHack** [KillWolfVlad/GitAhead-AUR#2]
Versions v1.4.13 and v1.4.14 also came out since the last commit.

I'll see if I can make a PR for v2.0.0.

**Comment by KillWolfVlad** [comment]
Other question: can we hack (or find crack) for new version?

> GitAhead 2.0 requires a new license!

I think they changed algorithm, so old keygen shouldn't work ;(

**Comment by WaveHack** [comment]
I'm not interested (nor do I condone) the hack you have or the license you have shared.

I just want to see it updated on the AUR.

**Comment by KillWolfVlad** [comment]
Oh, I understand. You nick is `WaveHack`, so I think that you a hacker)))

**Comment by WaveHack** [comment]
I am a hacker, but I try to be on the ethical and legal side of things. At least in public. ;)

**Comment by KillWolfVlad** [comment]
Interesting))) But I think, that cracks/keygens must be open source

**Comment by WaveHack** [comment]
Can you easily sniff or figure out what URL the update uses for the README? The versioning system they use on there is wonky.

https://gitahead.com/cgi-bin/update.py?platform=linux&version=1.4.12 shows version info for 2.0.0
https://gitahead.com/cgi-bin/update.py?platform=linux&version=1.4.121 shows condensed version info for 2.0.0
https://gitahead.com/cgi-bin/update.py?platform=linux&version=2.0.0 results in blank

**Comment by KillWolfVlad** [comment]
Updated in e2a0096
